public class Mengi2 {
    public static void main(String[] args) {
        System.out.println((int)(Math.random()*10)-2.5);
        System.out.println((int)(Math.random()*10)-2.5);
        System.out.println((int)(Math.random()*10)-2.5);
        System.out.println((int)(Math.random()*10)-2.5);
        System.out.println((int)(Math.random()*10)-2.5);
        System.out.println((int)(Math.random()*10)-2.5);
        System.out.println((int)(Math.random()*10)-2.5);
        System.out.println((int)(Math.random()*10)-2.5);
        System.out.println((int)(Math.random()*10)-2.5);
        System.out.println((int)(Math.random()*10)-2.5);
        System.out.println((int)(Math.random()*10)-2.5);
        System.out.println((int)(Math.random()*10)-2.5);
        System.out.println((int)(Math.random()*10)-2.5);
        System.out.println((int)(Math.random()*10)-2.5);
        System.out.println((int)(Math.random()*10)-2.5);
        System.out.println((int)(Math.random()*10)-2.5);
        System.out.println((int)(Math.random()*10)-2.5);
        System.out.println((int)(Math.random()*10)-2.5);
        System.out.println((int)(Math.random()*10)-2.5);
        System.out.println((int)(Math.random()*10)-2.5);
        System.out.println((int)(Math.random()*10)-2.5);
        System.out.println((int)(Math.random()*10)-2.5);
        System.out.println((int)(Math.random()*10)-2.5);
        System.out.println((int)(Math.random()*10)-2.5);
        System.out.println((int)(Math.random()*10)-2.5);
        System.out.println((int)(Math.random()*10)-2.5);
        System.out.println((int)(Math.random()*10)-2.5);
        System.out.println((int)(Math.random()*10)-2.5);
        System.out.println((int)(Math.random()*10)-2.5);
        System.out.println((int)(Math.random()*10)-2.5);
        System.out.println((int)(Math.random()*10)-2.5);
        System.out.println((int)(Math.random()*10)-2.5);
        System.out.println((int)(Math.random()*10)-2.5);
        System.out.println((int)(Math.random()*10)-2.5);
        System.out.println((int)(Math.random()*10)-2.5);
        System.out.println((int)(Math.random()*10)-2.5);
        System.out.println((int)(Math.random()*10)-2.5);
        System.out.println((int)(Math.random()*10)-2.5);
        System.out.println((int)(Math.random()*10)-2.5);
        System.out.println((int)(Math.random()*10)-2.5);
        System.out.println((int)(Math.random()*10)-2.5);
        System.out.println((int)(Math.random()*10)-2.5);
        System.out.println((int)(Math.random()*10)-2.5);
    }
}

/*
 * Sup homie
 */
